function guide4S

global gdeData4S
delete(findobj(0,'Tag', 'fig2'))
%% creates the prompt window that instructs the user 
gde = figure(2);
set(gde,'renderer','OpenGL','visible','off');
set(gde, 'Units', 'pixels')
set(gde,'menubar','none')
set(gde, 'Tag', 'fig2')

pan on;
pan off;

%% Defines an object that stores guide message data

gdeData4S = guide_message;

gdeData4S.msg1 = ['Welcome to the Four Spring Parallel Mechanism Designer! ' fprintf('%s\n%s') newline fprintf('%s\n%s') newline ...
    'The window titled "Figure 1" provides a graphical user interface for the design of a mechanism that realizes a desired stiffness behavior. ' ... 
    'The panel on the window far left allows program inputs to be provided as text. ' ...
    ['The panel on the far right provides a description of the design and the stiffness matrix, ' ...
    'calculated based on the design, to confirm that the desired behavior is realized. '] fprintf('%s\n%s') newline   fprintf('%s\n%s') newline...
    'To start, in the panel on the left, enter the desired stiffness matrix to be realized by the mechanism.  ' ...
    'Since passive realization requires the matrix to be symmetric positive definite, only the cells in the matrix upper triangle allow text input.  ' ...
    '(The cells in the lower triangle are automatically populated.)  ' ...
    ['An alert is provided if the desired matrix is not positive definite, ' ...
    'for which case the matrix entered must be modified prior to beginning the design process.']  fprintf('%s\n%s') newline fprintf('%s\n%s') newline ... ...
    'Once the matrix is entered, the location of the stiffness center is identified by a red star in a plot in the center panel.  ' ...
    'A red circle centered at this location is also generated.  ' ...
    'This circle roughly indicates the average perpendicular distance that the construction lines must have from the stiffness center. ' ...
    'At least one spring axis must intersect the circle and at least one spring axis must not intersect the circle. ' fprintf('%s\n%s') newline fprintf('%s\n%s') newline ...
    'Two red lines passing through the stiffness center are also generated. These lines seperate the coordinate plane into two regions. ' ...
    'Each region is made up of two cones that go off to infinty in opposite directions. ' ...
    'Each spring axis has a line perpendicular to it that also passes through the stiffness center. ' ...
    'The spring axes must be positioned such a way that there is at least one of these ' ...
    ['lines in each of the two regions created by the red lines on the plot. ' ...
    'This condition must be satisfied for the stiffness to be passively realized.'] fprintf('%s\n%s') newline fprintf('%s\n%s') newline ...
    'To begin the mechanism design process, the location of a construction point ' ...
    '(designated "P1") must be selected. P1 will be the location where the lines of action of springs 1 and 4 intersect.' ...
    'This selection can be made either by: 1) entering the X- and Y- Coordinates of the point in text fields in the far left panel (and clicking on Submit), or 2) ' ...
    'clicking a desired location on the plot in the center panel to define P1. ' ...
    'In the lower left panel, the size of the square plot area (+/- defined value for each axis) can be selected using the "Axes Scaler" text field; ' ... 
    'and the current cursor X- and Y- Positions are displayed in real time. ' ...
    'Using P1, a construction line (designated "L1") restricting the possible locations of the intersection of springs 2 and 3 is generated.'];

gdeData4S.msg2 = ['The location of P1 can be chnaged by either: 1) clicking on and dragging P1 to a new loation, or 2) pressing reset and selecting a new location for P1. ' ...
    'L1 will be automatically updated if P1 is moved. Once the location of P1 has been selected, a second construction point (designated "P2") needs to be placed. ' ...
    'P2 will be the intersection point of springs 2 and 3, and must lie on L1. The location of P2 can be selected by: ' ...
    '1) entering the X- and Y- Coordinates of the point in text fields in the far left panel (and clicking on Submit), or 2) ' ...
    'clicking a desired location on L1 on the plot in the center panel to define P1. Once P2 is placed a construction line associated with P2 (designated L2) is generated. ' ...
    'A dashed segment connecting P1 and P2 will also be generated'];

gdeData4S.msg3 = ['The location of P2 can be changed by clicking on and dragging P2 along L1. If P1 is clicked and dragged, P2 and L2 will be deleted. ' ...
    'L2 will automatically update if P2 is moved. A third construction line (designated "L3") must be placed. ' ...
    'This line constrains the possible locations of the intersections of springs 3 and 1. L3 cannot intersect the dashed line connecting P1 and P2. ' ...
    'Once L3 is placed, a construction point (designated "P3") will be generated. This point must be located on the opposite side of the dashed line segment ' ...
    'from the sitffness center. This can be acheived by seperating L3 and the dashed line segment with the stiffness center. ' ...
    'L3 can be defined by placing two nodes (designated "N1" and "N2") for the Line to pass through. To place N1, either: ' ...
    '1) entering the X- and Y- Coordinates of the point in text fields in the far left panel (and clicking on Submit), or 2) ' ...
    'clicking a desired location on the plot in the center panel to define N1.'];

gdeData4S.msg4 = ['The location of N1 can be chnged by cliking on and dragging N1. If P2 is clicked on and dragged, N1 will be deleted. ' ...
    'If P1 is clicked on and dragged, P2, L2, and N1 will be deleted. N2 can be placed by either ' ...
    '1) entering the X- and Y- Coordinates of the point in text fields in the far left panel (and clicking on Submit), or 2) ' ...
    'clicking a desired location on the plot in the center panel to define N1. After N2 is placed, L3 and P3 will be geneterated. ' ...
    'If L3 intersects the dashed segment or if the stiffness center and P3 are not seperated by the dashed line, P3 and L3 will be deleted ' ...
    'and will have to be placed again'];

gdeData4S.msg5 = ['L3 can be moved by: 1) clicking and dragging the Line, or 2) clicking and dragging either N1 or N2. ' ...
    'To complete the mechanism, a fourth construction point (designated "P4") must be placed. P4 is the intersection point ' ...
    'of springs 1 and 3 and must be located on the segment of L3 between L1 and L2. P4 can be placed by either: ' ...
    '1) entering the X- and Y- Coordinates of the point in text fields in the far left panel (and clicking on Submit), or 2) ' ...
    'clicking a desired location on L3 between L1 and L2.'];

gdeData4S.msg6 = ['The Mechanism is now complete! To modify the geometry of the mechanism, P4 can be clicked on and dragged. ' ...
    'If any previously deined point is clicked on, the program will return to that step of the synthesis process. ' ...
    'To restart the mechanism design process, click on the reset button.'];


%% creates a textbox in the window and sets the initial message
msg = uicontrol('Style', 'Text', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.026, ...
    'units', 'normalized', ...
    'String', gdeData4S.msg1, ...
    'Position', [0.01, 0.01, 0.98, 0.98], ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'msg', 'HorizontalAlignment','left');


%% Creates buttons to go backward and forward

next = uicontrol('Style', 'pushbutton', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'String', 'Next >', ...
    'units', 'normalized', ...
    'Position', [0.52, 0.05, 0.1, 0.05], ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0, 0, 0], ...
    'Callback', {@guideCallback4S, 'Next', msg});

Previous = uicontrol('Style', 'pushbutton', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'String', '< Previous', ...
    'units', 'normalized', ...
    'Position', [0.38, 0.05, 0.1, 0.05], ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0, 0, 0], ...
    'Callback', {@guideCallback4S, 'Previous', msg});






%% Sets the intial window position and size
resolution = get(0,'screensize');
set(gde,'position',[resolution(3)/13,resolution(4)/9,1200,670]);

set(gde,'visible','on'); hold on


end