function [] = framework()

close all force
clear all

userpath('clear')
userpath('reset')
addpath('PlanarComplianceApp/')

global dd1 dd2 dd3 dd4 dd5 dd6 dd7 dd8 val2 val3 val4 val5 val6 val7 val8

%val = value that user switched to in a drop down 
%dd = contents of the respective dropdown

fig = uifigure('Name', 'Planar Compliance App',...
    'Color', 'w', ...
    'Tag', 'fig', ...
    'Units', 'normalized');
fig.Position = [0.25 0.25 0.5 0.5];

gl = uigridlayout(fig,[3 1], ...
    'RowHeight', {80, '1x', 40},...
    'BackgroundColor','w');

txt = uitextarea(gl, 'FontSize', 20, ...
    'Editable', 'off', ...
    'HorizontalAlignment', 'center');
txt.Layout.Row = 1;
txt.Value = {['Welcome to the Planar Compliance Mechanism Geometry Designer. ' ...
    'Choose which type of geometry you would like to design below.']};

%% Gl1
gl1 = uigridlayout(gl, [5 3], ...
    'Rowheight', {'1x', 20, 20, 20, '1x'}, ...
    'BackgroundColor','w');
gl1.Layout.Row = 2;

dd1 = uidropdown(gl1, 'Value', '',...
    'Tag', 'dd1', ...
    'Editable', 'off', ...
    'Placeholder', 'Mechanism Type',...
    'Items', {'', 'Serial', 'Parallel', 'Multiserial'}, ...
    'ValueChangedFcn', {@typeSelected, 'dd1'});
dd1.Layout.Row = 3; dd1.Layout.Column = 1;

dd2 = uidropdown(gl1, 'Value', '',...
    'Enable', 'off', ...
    'Editable', 'off', ...
    'Placeholder', '',...
    'Items', {''}, ...
    'Tag', 'dd2', 'ValueChangedFcn', @DD2);
dd2.Layout.Row = 3; dd2.Layout.Column = 3;

dd3 = uidropdown(gl1, 'Value', '',...
    'Editable', 'off', ...
    'Placeholder', 'Number of Joints - Mechanism 1',...
    'Items', {'', '3', '4', '5', '6'}, ...
    'Visible', 'off', ...
    'Tag', 'dd3', 'ValueChangedFcn', @DD3);
dd3.Layout.Row = 2;dd3.Layout.Column = 3;


dd4 = uidropdown(gl1, 'Value', '',...
    'Editable', 'off', ...
    'Placeholder', 'Number of Joints - Mechanism 2',...
    'Items', {'', '3', '4', '5', '6'}, ...
    'Visible', 'off', ...
    'Tag', 'dd4', 'ValueChangedFcn', @DD4);
dd4.Layout.Row = 4;dd4.Layout.Column = 3;

dd5 = uidropdown(gl1, 'Value', '', ...
    'Editable', 'off', ...
    'Items', {'', 'Yes', 'No'}, ...
    'Placeholder', 'Are Joint Lengths Fixed?', ...
    'Tag', 'dd5', ...
    'ValueChangedFcn', {@typeSelected, 'dd5'}, ...
    'Visible', 'off');
dd5.Layout.Row = 3; dd5.Layout.Column = 2;

dd6 = uidropdown(gl1, 'Value', '', ...
    'Editable', 'off', ...
    'Items', {'', 'Rigid', 'Point'}, ...
    'Placeholder', 'Type of Contact', ...
    'Tag', 'dd6', ...
    'ValueChangedFcn', @DD6, ...
    'Visible', 'off');
dd6.Layout.Row = 3; dd6.Layout.Column = 2;

dd7 = uidropdown(gl1, 'Value', '', ...
    'Editable', 'off', ...
    'Items', {'', '2', '3', }, ...
    'Placeholder', 'Number of Mechanisms', ...
    'Tag', 'dd7', ...
    'ValueChangedFcn', {@typeSelected, 'dd7'}, ...
    'Visible', 'off');
dd7.Layout.Row = 3; dd7.Layout.Column = 2;

dd8 = uidropdown(gl1, 'Value', '', ...
    'Editable', 'off', ...
    'Items', {'', '3', '4', '5', '6'}, ...
    'Placeholder', 'Number of Joints - Mechanism 3', ...
    'Tag', 'dd8', ...
    'ValueChangedFcn', @DD8, ...
    'Visible', 'off');
dd8.Layout.Row = 4; dd8.Layout.Column = 3;

%%

startbtn = uibutton(gl, 'Text', 'Start', ...
    'FontSize', 20, ...
    'ButtonPushedFcn', {@Start, fig});
startbtn.Layout.Row = 3;

function DD2(~, event)
val2 = event.Value;
end 

function DD3(~, event)
val3 = event.Value;
end 

function DD4(~, event)
val4 = event.Value;
end 

function DD6(~, event)
val6 = event.Value;
end

function DD7(~, event)
val7 = event.Value;
end

function DD8(~, event)
val8 = event.Value;
end

end 
