function guide5J


global gdeData5J
delete(findobj(0,'Tag', 'fig2'))
%% creates the prompt window that instructs the user 
gde = figure(2);
set(gde,'renderer','OpenGL','visible','off');
set(gde, 'Units', 'pixels')
set(gde,'menubar','none')
set(gde, 'Tag', 'fig2')

pan on;
pan off;


%% Defines an object that stores guide message data

gdeData5J = guide_message;

gdeData5J.msg1 = ['  Welcome to the Five Joint Serial Mechanism Designer. ' ...
    'The panel to the left of the plot allows you to control the program. ' ...
    'The panel to the right of the plot shows you the specifications of your mechanism. ' ...
    'This includes the location of each joint, the neccesary compliance of each joint, and the compliance matrix calculated ' ...
    'using the joint compliances. The calculated compliance matrix is for confirmation that the joint compliances will realize the compliance matrix. ' ...
    'To enter the compliance matrix that you would like to realize, select the matrix cells on the diagonal and above the diagonal and enter your desired value. ' ...
    'This matrix must be symmetric positive definite because the joint compliances must be positive to passively realize the complaince matrix. ' ...
    'The program will automatically update off-diagonal values to keep the matrix symmetric. ' fprintf('%s\n%s') newline ...
    '   The red circle surrounding the compliance center is caculated using the eigenvalues of the compliance matrix. ' ...
    'At least one joint must be located inside the circle and at least one joint must be located outside of the circle for the compliance ' ...
    'to be passively realized. ' fprintf('%s\n%s') newline ...
    '   The four red lines surrounding the compliance center are also caluclated using the eigenvalues of the compliance matrix and are parallel to its eigenvectors. ' ...
    'for each set of parallel lines, at least one joint must be between the lines and at least one joint must be outside of the lines for the complinace to be ' ...
    'passively realized.' fprintf('%s\n%s') newline ...
    '   To begin, either select two points on the axes, or enter two ' ...
    'points and click submit. This will define the line of action of the first wrench, which will pass through joint 1 and joint 2. ', ...
    'The twist associated with wrench 1 will be plotted automatically.'];

gdeData5J.msg2 = ['Select or enter the coordinates of another point to define the line of action' ...
            ' of the first wrench. This line will pass through Joints 1 and 2. The twist associated with wrench 1 will be plotted automatically.'];

gdeData5J.msg3 = ['Select or enter the coordinates of another two points to define the line of action' ...
            ' of the second wrench. This line will pass through Joints 3 and 4. The twist asociated with wrench 2 will be plotted automatically'];

gdeData5J.msg4 = ['Select or enter the coordinates of another point to define the line of action' ...
            ' of the second wrench. This line will pass through Joints 3 and 4. The twist asociated with wrench 2 will be plotted automatically'];

gdeData5J.msg5 = ['Select or enter the coordinates of another point to define the position' ...
            ' of joint 5. Joint 5 must be on the same side of wrench 2 as twist 1'];

gdeData5J.msg6 = ['Select or enter the coordinates of another two points to define the line of action' ...
            ' of the third wrench. This line will pass through Joints 2 and 3. This wrench must satisfy part ii of condition 3 found in ' ...
            'the paper titled Geometry based synthesis of planar compliances with reduntand mechanisms having 5 compliant components.'];

gdeData5J.msg7 = ['Select or enter the coordinates of another point to define the line of action' ...
            ' of the third wrench.'];

gdeData5J.msg8 = ['Select or enter another point to define the line of action' ...
            ' of the fourth wrench. If this line does not itersect the triangle defined by the other ' ...
            'three joints, then the twist associated with the line must be contained in the triangle.' ...
            ' If this line intersects the triangle, then the twist associated with the line must be ' ...
            'be in the region defined by the verticies of the triangle.'];


%% creates a textbox in the window and sets the initial message
msg = uicontrol('Style', 'Text', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'Fontsize', 0.035, ...
    'units', 'normalized', ...
    'String', gdeData5J.msg1, ...
    'Position', [0.01, 0.01, 0.98, 0.98], ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'msg', ...
    'HorizontalAlignment','left');


%% Creates buttons to go backward and forward

next = uicontrol('Style', 'pushbutton', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'String', 'Next >', ...
    'units', 'normalized', ...
    'Position', [0.52, 0.05, 0.1, 0.05], ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0, 0, 0], ...
    'Callback', {@guideCallback5J, 'Next', msg});

Previous = uicontrol('Style', 'pushbutton', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'String', '< Previous', ...
    'units', 'normalized', ...
    'Position', [0.38, 0.05, 0.1, 0.05], ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0, 0, 0], ...
    'Callback', {@guideCallback5J, 'Previous', msg});






%% Sets the intial window position and size
resolution = get(0,'screensize');
set(gde,'position',[resolution(3)/13,resolution(4)/9,1200,670]);

set(gde,'visible','on'); hold on

end