function guide3S

global gdeData3S
delete(findobj(0,'Tag', 'fig2'))
%% creates the prompt window that instructs the user 
gde = figure(2);
set(gde,'renderer','OpenGL','visible','off');
set(gde, 'Units', 'pixels')
set(gde,'menubar','none')
set(gde, 'Tag', 'fig2')

pan on;
pan off;

%% Defines an object that stores guide message data

gdeData3S = guide_message;

gdeData3S.msg1 = ['Welcome to the Three Spring Parallel Mechanism Designer! ' fprintf('%s\n%s') newline fprintf('%s\n%s') newline ...
    'The window titled "Figure 1" provides a graphical user interface for the design of a mechanism that realizes a desired stiffness behavior. ' ... 
    'The panel on the window far left allows program inputs to be provided as text. ' ...
    'The panel on the far right provides a description of the design and the stiffness matrix, calculated based on the design, to confirm that the desired behavior is realized. ' fprintf('%s\n%s') newline   fprintf('%s\n%s') newline...
    'To start, in the panel on the left, enter the desired stiffness matrix to be realized by the mechanism.  ' ...
    'Since passive realization requires the matrix to be symmetric positive definite, only the cells in the matrix upper triangle allow text input.  (The cells in the lower triangle are automatically populated.)  ' ...
    'An alert is provided if the desired matrix is not positive definite, for which case the matrix entered must be modified prior to beginning the design process.'  fprintf('%s\n%s') newline fprintf('%s\n%s') newline ... ...
    'Once the matrix is entered, the location of the stiffness center is identified by a red star in a plot in the center panel.  A red circle centered at this location is also generated.  ' ...
    'This circle roughly indicates the average perpendicular distance that the construction lines must have from the compliance center. ' ...
    'At least one spring axis must intersect the circle and at least one spring axis must not intersect the circle. ' fprintf('%s\n%s') newline fprintf('%s\n%s') newline ...
    'Two red lines passing through the stiffness center are also generated. These lines seperate the coordinate plane into two regions. ' ...
    'Each region is made up of two cones that go off to infinty in opposite directions. ' ...
    'Each spring axis has a line perpendicular to it that also passes through the stiffness center. The spring axes must be positioned such a way that there is at least one of these ' ...
    'lines in each of the two regions created by the red lines on the plot. This condition must be satisfied for the stiffness to be passively realized.' fprintf('%s\n%s') newline fprintf('%s\n%s') newline ...
    'To begin the mechanism design process, the location of two nodes, which the first spring axis intersects, can be selected using the guidance provided by the circle and the lines intersecting at the stiffness center.  ' ...
    'This selection can be made either by: 1) entering the X- and Y- Coordinates of the nodes in text fields in the far left panel (and clicking on Submit), or 2) ' ...
    'clicking a desired location on the plot in the center panel to define each node.  In the lower left panel, the size of the square plot area (+/- defined value for each axis) can be selected using the "Axes Scaler" text field; ' ... 
    'and the current cursor X- and Y- Positions are displayed in real time.'  fprintf('%s\n%s') newline  fprintf('%s\n%s') newline ...
    'Using the selected first spring axis, a construction point (labeled "T1") restricting the possible locations of spring axes 2 and 3 is generated.'];

gdeData3S.msg2 = ['The location of the first node can be moved by clicking the Reset button '...
    'and then either: 1) entering new node 1 X- and Y- Coordinates in text fields (and clicking on Submit) or 2) by clicking ' ...
    'a new location on the plot in the center panel. The second node location can be selected by: 1) entering the node 2 X- and Y- ' ...
    'Coordinates and then clicking on Submit or 2) clicking a desired location on the plot in the center panel. ' ... 
    'Once node 2 is placed, the first spring axis will automatically be plotted passing through node 1 and node 2. ' ...
    'A construction point (labeled "T1"), constraining the placement of spring axes 2 and 3, will also be generated.'];


gdeData3S.msg3 = ['The location and orientation of the first spring axis can be changed by: 1) clicking and dragging the nodes associated with it to a new ' ...
    'location, 2) clicking and dragging the line to a new location, or 3) clicking the reset button and entering new X- and Y- coordinateds for node 1 and 2 in the text fields. ' ...
    'If spring axis one is moved, T1 will be automatically updated. The second spring axis must intersect T1. ' ...
    'To select spring axis 2, either: 1) enter the X- and Y- coordinates of a third node, or 2) click a location on the plot in the center panel to select node 3. ' ...
    'Once node 3 is selected, spring axis 2 (passing through node 3 and T1) will be generated. A construction point associated with spring axis ' ...
    '2 (labeled "T2") will also be generated. T2 constrains the placement of spring axis 3. Spring axis 3 must pass through T1 and T2. Since ' ...
    'there is only one possible placement for spring axis 3 given by T1 and T2, spring axis three will be automatically generated.'];

gdeData3S.msg4 = ['The mechanism is now complete! ' ...
    'To change the geometry of the mechanism, node 3 can be clicked on and dragged to a new location. ' ...
    'If node 1, node 2, or spring axis 1 are clicked on and dragged, spring axes 2 and 3 and T2 will be deleted. ' ... 
    'T1 will be automatically updated. To restart the mechanism design process, click on Reset.'] ;


%% creates a textbox in the window and sets the initial message
msg = uicontrol('Style', 'Text', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'Fontsize', 0.026, ...
    'units', 'normalized', ...
    'String', gdeData3S.msg1, ...
    'Position', [0.01, 0.01, 0.98, 0.98], ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'msg', ... 
    'HorizontalAlignment','left');


%% Creates buttons to go backward and forward

next = uicontrol('Style', 'pushbutton', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'String', 'Next >', ...
    'units', 'normalized', ...
    'Position', [0.52, 0.05, 0.1, 0.05], ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0, 0, 0], ...
    'Callback', {@guideCallback3S, 'Next', msg});

Previous = uicontrol('Style', 'pushbutton', ...
    'Parent', gde, ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'String', '< Previous', ...
    'units', 'normalized', ...
    'Position', [0.38, 0.05, 0.1, 0.05], ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0, 0, 0], ...
    'Callback', {@guideCallback3S, 'Previous', msg});

%% Sets the intial window position and size
resolution = get(0,'screensize');
set(gde,'position',[resolution(3)/13,resolution(4)/9,1200,670]);

set(gde,'visible','on'); hold on

end