function [] = Synthesis3J()

%%%%%%

addpath('PlanarComplianceApp/Serial3JSynthesis/')
addpath('PlanarComplianceApp/General_Functions/')
clearvars -global

fig = figure(1); clf;
set(fig,'Name','3 Joint Serial Mechanism','NumberTitle','on');
set(fig,'units','pixels');
set(fig,'renderer','OpenGL','visible','off');
set(fig,'SizeChangedFcn', {@cTableResize, fig});

pan on;
pan off;

global phase drag1 drag2 C
K = [3 -2 1; -2 6 5; 1 5 9];
C = inv(K);

phase = 0;
drag1 = 0;
drag2 = 0;

% phase 0 - Node 1 has not been placed
% phase 1 - Node 2 has not been placed
% phase 2 all three nodes are placed


z = 6;

ax = axes();
set(ax, 'Parent', fig)
linkaxes(ax);
axis([-z z -z z]);
set(ax,'units','normalized')
set(ax,'Position',[0.285, 0.05, 0.43, 0.9])
grid on; grid minor; box on;
%set(ax,'dataaspectratio',[1 1 1]);
axis equal; hold on

set(ax,'XLimMode','manual');
set(ax,'YLimMode','manual');
set(fig,'WindowButtonDownFcn',{@MouseClick, ax});
set(fig,'WindowButtonMotionFcn',{@MouseDrag, ax});
set(fig,'WindowButtonUpFcn',{@MouseRelease, ax});

set(fig,'menubar','none');


scatter(ax, 0,0,'+','markerfacecolor',[0 0 0],'sizedata',120,'markeredgecolor',[0 0 0]);

set(ax,'FontSize',15); % label font  %%%%%%%%%%

%Creates a home buttom
home = uicontrol('Style', 'pushbutton', ...
    'String','Home','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.65, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.025 0.93 0.1 0.05], ...
    'Callback',{@UIcallback3J,0,'Home'});

open_gde = uicontrol('Style', 'pushbutton', ...
    'String','Open Guide','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.55, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.145 0.93 0.1 0.05], ...
    'Callback',{@UIcallback3J,0,'open_gde'});

%% hp 
%creates the input pannel 
hp = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','panel',...
    'title','Input',...
    'BackgroundColor','white',...
    'Position',[0.01 0.02 0.25 0.9]);    %'Position',[hfw hfh 2*w 60]); 

%Creates the input table for the compliance matrix
table = uitable('units','normalized',...
            'parent',hp,...
            'Tag', 'table', ...
            'position',[0.1 0.78 0.8 0.15],...
            'Data',K,...
            'Rowname',[],...
            'FontUnits','normalized', ...
            'FontSize', 0.2, ...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[true true true],...
            'CellEditCallback',{@UIcallback3J,ax,'c'},...
            'SelectionHighlight','off');


%Creates a label for the compliance matrix table 
clab = uicontrol('Style','text', 'Parent',hp, ...
    'Units', 'normalized', ...
    'String', 'Compliance Matrix', ...
    'Position', [0.1 0.928 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);
        
%Creates an input box for the joint x coordinate
jx = uicontrol('Style', 'edit', ...
    'String', '', 'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'tag', 'Jx', ...
    'Position', [0.1 0.55 0.4 0.06]);

%creates an input box for the joint y coordinate
jy = uicontrol('Style', 'edit', ...
    'String', '', 'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'tag', 'Jy', ...
    'Position', [0.5 0.55 0.4 0.06]);

%Creates a label for the x input box
jlabx = uicontrol('Style', 'text', ...
    'String', 'Joint 1 X-Coordinate', ...
    'Units','normalized', 'FontUnits', 'normalized', ...
    'FontSize', 0.4, 'Parent', hp, ...
    'tag', 'JX', ...'
    'Position', [0.1 0.608 0.4 0.05]);

%Creates a label for the y input box
jlaby = uicontrol('Style', 'text', ...
    'String', 'Joint 1 Y-Coordinate', ...
    'Units','normalized', 'FontUnits', 'normalized', ...
    'FontSize', 0.4, 'Parent', hp, ...
    'tag', 'JY', ...
    'Position', [0.5 0.608 0.4 0.05]);

%Creates label for the box that shows the cursor x position
xlab = uicontrol('Style', 'text', ...
    'Tag', 'xalb', ...
    'String', 'X-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.35 0.385 0.3 0.05]);

%Creates a box that shows the cursor x position
xpos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'xpos', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...
    'Position', [0.35 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates a label for the box that shows the cursor y position
ylab = uicontrol('Style', 'text', ...
    'Tag', 'ylab', ...
    'String', 'Y-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.65 0.385 0.3 0.05]);

%creates a box that shows the cursor y position
ypos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'ypos', ...
    'units', 'Normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...]
    'Position', [0.65 0.34 0.3 0.05], ...
    'Enable','inactive');


%Creates the box for updating the axes scalar
scalar = uicontrol('Style','edit','string','6',...
    'parent', hp, ...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.34 0.3 0.05],...
    'tag','dim',...
    'Callback',{@UIcallback3J,ax,'dim'});                   

%Creates a label for the axes scalar box
scalarlab = uicontrol('Style','text','string','Axes Scaler: ',...
    'HorizontalAlignment', 'center', ...
    'parent', hp, ...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.385 0.3 0.05],...
    'tag','dimlabel');

%Creates the submit button
sbmt = uicontrol('Style', 'pushbutton', ...
    'Parent', hp, 'Units', 'normalized', ...
    'Position', [0.1 0.125 0.35 0.09], ...
    'String', 'Submit', ...
    'Tag', ' Submit', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'Callback', {@UIcallback3J, ax, 'Submit'});             

%Creates the reset button
rst = uicontrol('Style','pushbutton',...
    'parent', hp, ...
    'String','Reset',...
    'units','normalized',...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'position',[0.55 0.125 0.35 0.09],...
    'fontunits','normalized',...
    'fontsize',0.5,...
    'tag','reset',...
    'value',0,...
    'Callback',{@UIcallback3J,ax,'reset'});


%% hp 2
%Creates a pannel for the user to view the output
hp2 = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','panel2',...
    'title','Output',...
    'BackgroundColor','white',...
    'Position',[0.74 0.02 0.25 0.9]);

%gets the compliant center coordinates
[cx,cy] = compliantCenter(C, ax);

%formats the compliant center coordinates
cxs = sprintf('%0.2f', cx);
cys = sprintf('%0.2f', cy);
Jout = {cxs,'','','';
        cys,'','',''}; 

%Creates a table that outputs the joint coordinates
Jtab = uitable('units','normalized',...
            'parent',hp2,...
            'position',[0.05 0.812 0.9 0.13], ...
            'Data',Jout,...
            'tag','jout',...
            'FontUnits','normalized', ...
            'FontSize', 0.23, ...
            'Rowname',{'X','Y'},...
            'ColumnName',{'Cc','J1','J2','J3'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off',...
            'ColumnWidth',{45 45 45 45}); 

%creates a label for the output table 
Jlab = uicontrol('Style','text', ...
    'Parent',hp2, ...
    'Units', 'normalized', ...
    'String', 'Joint Positions', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.94 0.9 0.04]);

%Creates a label for the joint compliances
compLab = uicontrol('Style', 'Text', ...
    'Parent', hp2, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint Compliance', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.72 0.9 0.04]);

%creates an ouput box for joint compliance 1
comp1 = uicontrol('Style', 'text', ...
    'Parent', hp2, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.679 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp1');

%Creates a label for joint 1 compliance
comp1lab = uicontrol('Style', 'Text', ...
    'Parent', hp2, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.679 0.25 0.04]);

%creates an ouput box for joint 2 compliance
comp2  = uicontrol('Style', 'text', ...
    'Parent', hp2, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.638 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp2');

%Creates a label for joint 2 compliance 
comp2lab = uicontrol('Style', 'Text', ...
    'Parent', hp2, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.638 0.25 0.04]);

%creates an ouput box for joint 3 compliance
comp3 = uicontrol('Style', 'text', ...
    'Parent', hp2, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.597 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp3');

%Creates a label for joint 3 compliance
comp3lab = uicontrol('Style', 'Text', ...
    'Parent', hp2, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.597 0.25 0.04]);

%Creates a table for the Calculated compliance matrix output
Cout = uitable('units','normalized',...
            'parent',hp2,...
            'Tag', 'Cout', ...
            'position',[0.1 0.35 0.8 0.15],...
            'Data',{'', '', ''; '', '', ''; '', '', ''},...
            'Rowname',[],...
            'FontUnits','normalized', ...
            'FontSize', 0.2, ...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[false false false],... 
            'SelectionHighlight','off');

%creats a label for the C out table 
Clab = uicontrol('Style','text', 'Parent',hp2, ...
    'Units', 'normalized', ...
    'String', 'Calculated Compliance Matrix', ...
    'Position', [0.1 0.5 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);



%%



% plots compliance center
    [x,y] = compliantCenter(C, ax);
    scatter(ax, x,y,'*','markerfacecolor','red','sizedata',100,'markeredgecolor','red','tag','cpoint');

%Sets the intial window position and size
resolution = get(0,'screensize');
set(fig,'position',[resolution(3)/12,resolution(4)/8,1200,670]);

set(fig,'visible','on'); hold on
set(fig,'menubar','figure')

%opens the guide message window
guide3J()

end
