function [] = Synthesis6S()

addpath('PlanarComplianceApp/Parallel6SSynthesis/')
addpath('PlanarComplianceApp/General_Functions/')


clearvars -global

%Phase = 1 - nothing has happened

%Phase = 2 - T12 has been placed

%Phase = 3 - T34 has been placed

%Phase = 4 - Wrench 1 has been defined passing through T12

%Phase = 5 - Wrench 2 has been defined passing through T12

%Phase = 6 - Wrench 3 has been defined passing through T34

%Phase = 7 - Wrench 4 has been defined passing through T34. the quadratic
%curve h1234 has been plotted. Check that wrench 1-4 satisfies the spring 
%distribution conditons descibed in section 2.4

%Phase = 8 - T56 has been placed (Judiciously)

%Phase = 9 - w5 has been defined passing through T56

%Phase = 10 - w6 has been defined passing through T56 %Check that wrench 5
%and 6 satisfy the condition in step 4 of the synthesis. Display the spring
%constants and prompt the user to adjust w5 and w6 such that their
%constants have the same sign outputs are shown



global phase dragN dragL K
%C = [0.03, 0, 0; 0, 5, -0.56; 0, -0.56, 0.08];
%K = inv(C);
%K = [50,0,0; 0,0.8043, 3.9130;0,3.9130,21.7391];
K = [3, -2, -8; -2, 6, 11; -8, 11, 30];

phase = 1;
dragN = [0;0;0;0;0;0;0;0;0];
dragL = [0;0;0;0;0;0];

fig = figure(1); clf;
set(fig,'Name','Realization of a 6 Spring Parallel Mechanism','NumberTitle','on');
set(fig,'units','pixels');
set(fig,'renderer','OpenGL','visible','off');
set(fig,'SizeChangedFcn', {@cTableResize, fig});

pan on;
pan off;

z = 6;

ax = axes();
linkaxes(ax);
axis([-z z -z z]);
set(ax, 'Units', 'normalized')
set(ax,'Position',[0.285, 0.05, 0.43, 0.9])
grid on; grid minor; box on;
axis equal; hold on;

set(ax,'XLimMode','manual');
set(ax,'YLimMode','manual');
set(fig,'WindowButtonDownFcn',{@MouseClick, ax})
set(fig,'WindowButtonMotionFcn',{@MouseDrag, ax})
set(fig,'WindowButtonUpFcn',@MouseRelease);
set(fig,'menubar','none');
origin = scatter(0,0,'+','markerfacecolor',[0 0 0],'sizedata',120,'markeredgecolor',[0 0 0]);
uistack(origin, 'bottom');

p1 = plot([0, 0], [0.0001, 0], 'Color', [0 0.4470 0.7410], 'LineWidth', 2);
p2 = plot([0, 0], [0.0001, 0], 'Color', [0.9290 0.6940 0.1250], 'LineWidth', 2);
p3 = plot([0, 0], [0.0001, 0], 'Color', [0.8500 0.3250 0.0980], 'LineWidth', 2);
p4 = plot([0, 0], [0.0001, 0], 'Color', [0.4940 0.1840 0.5560], 'LineWidth', 2);
p5 = plot([0, 0], [0.0001, 0], 'Color', [0.4660 0.6740 0.1880], 'LineWidth', 2);
p6 = plot([0, 0], [0.0001, 0], 'Color', [0.3010 0.7450 0.9330], 'LineWidth', 2);

leg = legend('', 'wrench 1', 'wrench 2', 'wrench 3', 'wrench 4', 'wrench 5', 'wrench 6');
leg.AutoUpdate = "off";


%defines the home button
home = uicontrol('Style', 'pushbutton', ...
    'String','Home','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.65, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.025 0.93 0.1 0.05], ...
    'Callback',{@UICallback6S,0,'Home'});


open_gde = uicontrol('Style', 'pushbutton', ...
    'String','Open Guide','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.55, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.145 0.93 0.1 0.05], ...
    'Callback',{@UICallback6S,0,'open_gde'});


%Defines the entry boxes for the quadratic curves
entry1lab = uicontrol('Style','text', 'Parent', fig, ...
    'Units', 'normalized', ...
    'String', 'Wrench: ', ...
    'Position', [0.3 0.93 0.1 0.05], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'ent1lab', ...
    'Visible', 'off');

%Creates an input box for stiffnes 1
ent1 = uicontrol('Style', 'edit', ...
    'Parent', fig, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.405 0.93 0.05 0.05], ...
    'Tag', 'ent1', ...
    'Visible', 'off');

%Defines the entry boxes for the quadratic curves
entry2lab = uicontrol('Style','text', 'Parent', fig, ...
    'Units', 'normalized', ...
    'String', 'Wrench: ', ...
    'Position', [0.5 0.93 0.1 0.05], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'ent2lab', ...
    'Visible', 'off');

%Creates an input box for stiffnes 1
ent2 = uicontrol('Style', 'edit', ...
    'Parent', fig, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.605 0.93 0.05 0.05], ...
    'Tag', 'ent2', ...
    'Visible', 'off');

%% hp

%Creates a panel for the input
hp = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','hp',...
    'title','Inputs',...
    'BackgroundColor','white',...
    'Position',[0.01 0.02 0.25 0.9]);


%Creates a table for the user to input the compliance matrix
table = uitable('units','normalized',...
            'parent',hp,...
            'position',[0.1 0.782 0.8 0.15],...
            'FontUnits', 'normalized', ...
            'fontsize',0.23,...
            'Data',K,...
            'Rowname',[],...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[true true true],...
            'CellEditCallback',{@UICallback6S,ax,'c'},...
            'SelectionHighlight','off',...
            'ColumnWidth',{55 55 55}, ...
            'Tag', 'table');

%Creates a label for the table created right before this
Klab = uicontrol('Style','text', 'Parent',hp, ...
    'Units', 'normalized', ...
    'String', 'Stiffness Matrix', ...
    'Position', [0.1 0.93 0.8 0.04], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.725);

%Creates a label for the x inputs 
xInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.63 0.3 0.05], ...
    'String', 'X');

%creates a label for the y inputs
yInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.63 0.3 0.05], ...
    'String', 'Y');

%Creates a label for the point 1 inputs 
Pt1Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.58 0.3 0.05], ...
    'String', 'Point 1');

%Creates an input box for point 1 x
pt1x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.58 0.3 0.05], ...
    'Tag', 'pt1x');

%creates an input box for point 1 y
pt1y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.58 0.3 0.05], ...
    'Tag', 'pt1y');

%Creates a label for the point 2 inputs
Pt2Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.53 0.3 0.05], ...
    'String', 'Point 2');

%creates an input box for point 2 x
pt2x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.53 0.3 0.05], ...
    'Tag', 'pt2x');

%creates an input box for point 2 y
pt2y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.53 0.3 0.05], ...
    'Tag', 'pt2y');

%Creates label for the box that shows the cursor x position
xlab = uicontrol('Style', 'text', ...
    'Tag', 'xalb', ...
    'String', 'X-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.35 0.385 0.3 0.05]);

%Creates a box that shows the cursor x position
xpos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'xpos', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...
    'Position', [0.35 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates a label for the box that shows the cursor y position
ylab = uicontrol('Style', 'text', ...
    'Tag', 'ylab', ...
    'String', 'Y-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.65 0.385 0.3 0.05]);

%creates a box that shows the cursor y position
ypos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'ypos', ...
    'units', 'Normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...]
    'Position', [0.65 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates the box for updating the axes scalar
scalar = uicontrol('Style','edit','string','6',...
    'parent', hp, ...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.34 0.3 0.05],...
    'tag','dim',...
    'Callback',{@UICallback6S,ax,'dim'});                   

%Creates a label for the axes scalar box
scalarlab = uicontrol('Style','text','string','Axes Scaler:',...
    'HorizontalAlignment', 'center', ...
    'parent', hp, ...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.385 0.3 0.05],...
    'tag','dimlabel');

%Creates a reset button
rst = uicontrol('Style','pushbutton',...
    'parent',hp,...
    'String','Reset',...
    'units','normalized',...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'position',[0.55 0.16 0.35 0.09],...
    'fontunits','normalized',...
    'fontsize',0.5,...
    'tag','reset',...
    'value',0,...
    'Callback',{@UICallback6S,ax,'reset'});

%Creates the submit button
sbmt = uicontrol('Style', 'pushbutton', ...
    'Parent', hp, 'Units', 'normalized', ...
    'Position', [0.1 0.16 0.35 0.09], ...
    'String', 'Submit', ...
    'Tag', ' Submit', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'Callback', {@UICallback6S, ax, 'Submit'}); 



%% hp2

%Creates a panel for the output
hpout = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','hpout',...
    'title','Outputs',...
    'BackgroundColor','white',...
    'Position',[0.74 0.02 0.25 0.95]);


%creates a label for the table above
linLab = uicontrol('Style','text', ...
    'Parent',hpout, ...
    'Units', 'normalized', ...
    'String', 'Spring Line of Action Equations', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.94 0.9 0.04]);

%creates an ouput box for line equation 1
lin1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.899 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin1');

%Creates a label for line equation 1
lin1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.899 0.25 0.04]);

%creates an ouput box for line equation 2
lin2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.858 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin2');

%Creates a label for line 2 equation
lin2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.858 0.25 0.04]);

%creates an ouput box for line equation 3
lin3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.818 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin3');

%Creates a label for line 3 equation
lin3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.818 0.25 0.04]);


%creates an ouput box for line equation 4
lin4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.777 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin4');

%Creates a label for line 4 equation
lin4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 4', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.777 0.25 0.04]);

%Creates an output box for lin equation 5
lin5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.736 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin5');

%Creates a label for line 5 equation
lin5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 5', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.736 0.25 0.04]);

%Creates an output box for lin equation 6
lin6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.695 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin6');

%Creates a label for line 6 equation
lin6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 6', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.695 0.25 0.04]);

%Creates a label for the spring wrenches
wrenchlab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Transpose Spring Wrenches', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.638 0.9 0.04]);

%creates an ouput box for spring wrench 1
wrench1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.597 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench1');

%Creates a label for spring wrench 1
wrench1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.597 0.25 0.04]);

%creates an ouput box for spring wrench 2
wrench2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.556 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench2');

%Creates a label for spring wrench 2
wrench2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.556 0.25 0.04]);

%creates an ouput box for spring wrench 3
wrench3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.515 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench3');

%Creates a label for spring wrench 3
wrench3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.515 0.25 0.04]);

%creates an ouput box for spring wrench 4
wrench4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.475 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench4');

%Creates a label for spring wrench 3
wrench4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 4', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.475 0.25 0.04]);

%creates an ouput box for spring wrench 5
wrench5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.438 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench5');

%Creates a label for spring wrench 5
wrench5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 5', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.435 0.25 0.04]);

%creates an ouput box for spring wrench 6
wrench6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.395 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench6');

%Creates a label for spring wrench 6
wrench6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 6', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.395 0.25 0.04]);

%Creates a label for the spring stiffnesses
stiffLab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring Stiffness', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.338 0.9 0.04]);

%creates an ouput box for spring stiffness 1
stiff1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.298 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff1');

%Creates a label for spring stiffness 1
stiff1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.298 0.25 0.04]);

%creates an ouput box for Spring stiffness 2
stiff2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.257 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff2');

%Creates a label for spring 2 stiffness
stiff2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.257 0.25 0.04]);

%creates an ouput box for spring stiffness 3
stiff3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.217 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff3');

%Creates a label for spring stiffness 3
stiff3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.217 0.25 0.04]);


%creates an ouput box for spring stifffness 4
stiff4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.75 0.298 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff4');

%Creates a label for spring stiffness 4
stiff4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 4', ...
    'FontSize', 0.7, ...
    'Position', [0.5 0.298 0.25 0.04]);

%creates an ouput box for spring stifffness 5
stiff5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.75 0.257 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff5');

%Creates a label for spring stiffness 5
stiff5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 5', ...
    'FontSize', 0.7, ...
    'Position', [0.5 0.257 0.25 0.04]);

%creates an ouput box for spring stifffness 6
stiff6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.75 0.217 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff6');

%Creates a label for spring stiffness 6
stiff6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 6', ...
    'FontSize', 0.7, ...
    'Position', [0.5 0.217 0.25 0.04]);

%Creates a table to output the calculated stiffness matrix
Kout = uitable('units','normalized',...
            'parent',hpout,...
            'Tag', 'Kout', ...
            'position',[0.1 0.02 0.8 0.15],...
            'Data',{'', '', ''; '', '', ''; '', '', ''},...
            'Rowname',[],...
            'FontUnits','normalized', ...
            'FontSize', 0.2, ...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[false false false],... 
            'SelectionHighlight','off');

%creates a label for the K out table 
Klab = uicontrol('Style','text', 'Parent',hpout, ...
    'Units', 'normalized', ...
    'String', 'Calculated Siffness Matrix', ...
    'Position', [0.1 .1675 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);





%%

%Displays the stiffness center on the plot
[x,y,K] = stiffnessCenter(K, ax);
scatter(x,y,'*','markerfacecolor','red','sizedata',100,'markeredgecolor','red','tag','cpoint');

%Sets the position and size of the main window
resolution = get(0,'screensize');
set(fig,'position',[resolution(3)/12,resolution(4)/8,1200,670]);

%Opens the guide window
guide6S()

set(fig,'visible','on'); hold on;
set(gcf,'menubar','figure');


end