function Synthesis3J_3Finger
addpath('PlanarComplianceApp/MultiSerial3J_3Finger/')
addpath('PlanarComplianceApp/General_Functions/')

clearvars -global

%Phase = 2 - nothing has happened

%Phase = 3 - T12 has been placed

%Phase = 4 - T34 has been placed

%Phase = 5 - Wrench 1 has been defined passing through T12

%Phase = 6 - Wrench 2 has been defined passing through T12

%Phase = 7 - Wrench 3 has been defined passing through T34

%Phase = 8 - Wrench 4 has been defined passing through T34. the quadratic
%curve h1234 has been plotted. Check that wrench 1-4 satisfies the spring 
%distribution conditons descibed in section 2.4

%Phase = 9 - T56 has been placed (Judiciously)

%Phase = 10 - w5 has been defined passing through T56

%Phase = 11 - w6 has been defined passing through T56 %Check that wrench 5
%and 6 satisfy the condition in step 4 of the synthesis. Display the spring
%constants and prompt the user to adjust w5 and w6 such that their
%constants have the same sign outputs are shown



global phase dragN dragL K V3J_3F
%C = [0.03, 0, 0; 0, 5, -0.56; 0, -0.56, 0.08];
%K = inv(C);
%K = [50,0,0; 0,0.8043, 3.9130;0,3.9130,21.7391];
%K = [3, -2, -8; -2, 6, 11; -8, 11, 30];
K = [33.3333, 0, 0; 0, 0.9259, 6.4815; 0, 6.4815, 57.8704];

phase = 1;
dragN = [0;0;0;0;0;0;0;0;0];
dragL = [0;0;0;0;0;0];

V3J_3F = verticies;
V3J_3F.x = [];
V3J_3F.y = [];

fig = figure(1); clf;
set(fig,'Name','Realization of a 3 Joint, 3 Finger, Multiserial Mechanism','NumberTitle','on');
set(fig,'units','pixels');
set(fig,'renderer','OpenGL','visible','off');
set(fig,'SizeChangedFcn', {@cTableResize, fig});
set(fig, 'Tag', 'fig')

pan on;
pan off;

z = 6;

ax = axes();
linkaxes(ax);
axis([-z z -z z]);
set(ax, 'Units', 'normalized')
set(ax,'Position',[0.285, 0.05, 0.43, 0.9])
grid on; grid minor; box on;
axis equal; hold on;

origin = scatter(0,0,'+','markerfacecolor',[0 0 0],'sizedata',120,'markeredgecolor',[0 0 0]);
uistack(origin, 'bottom');

set(ax,'XLimMode','manual');
set(ax,'YLimMode','manual');
set(ax,'ButtonDownFcn',{@MouseClick, ax})
set(fig,'WindowButtonMotionFcn',{@MouseDrag, ax})
set(fig,'WindowButtonUpFcn',{@MouseRelease, ax});
set(fig,'menubar','none');

% Creates a legend with only the desired values present
p1 = plot([0, 0], [0.0001, 0], 'Color', [0 0.4470 0.7410], 'LineWidth', 2, 'DisplayName', 'L1', 'Tag', 'M1');
p2 = plot([0, 0], [0.0001, 0], 'Color', [0.9290 0.6940 0.1250], 'LineWidth', 2, 'DisplayName', 'L2', 'Tag', 'M2');
p3 = plot([0, 0], [0.0001, 0], 'Color', [0.8500 0.3250 0.0980], 'LineWidth', 2, 'DisplayName', 'L3', 'Tag', 'M3');
p4 = plot([0, 0], [0.0001, 0], 'Color', [0.4940 0.1840 0.5560], 'LineWidth', 2, 'DisplayName', 'L4', 'Tag', 'M4');
p5 = plot([0, 0], [0.0001, 0], 'Color', [0.4660 0.6740 0.1880], 'LineWidth', 2, 'DisplayName', 'L5', 'Tag', 'M5');
p6 = plot([0, 0], [0.0001, 0], 'Color', [0.3010 0.7450 0.9330], 'LineWidth', 2, 'DisplayName', 'L6', 'Tag', 'M6');

leg = legend;
leg.AutoUpdate = "off";
Ls = leg.String;
Lss = size(Ls);
for i = 1:Lss(2)
    if ~strcmp(Ls(1, i), 'L1') && ~strcmp(Ls(1, i), 'L2') && ~strcmp(Ls(1, i), 'L3') && ...
            ~strcmp(Ls(1, i), 'L4') && ~strcmp(Ls(1, i), 'L5') && ~strcmp(Ls(1, i), 'L6')
        Ls(1, i) = {''};
    end
end
legend(Ls)




%defines the home button
home = uicontrol('Style', 'pushbutton', ...
    'String','Home','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.65, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.025 0.93 0.1 0.05], ...
    'Callback',{@UICallback3J_3Finger,0,'Home'});

open_gde = uicontrol('Style', 'pushbutton', ...
    'String','Open Guide','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.55, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.145 0.93 0.1 0.05], ...
    'Callback',{@UICallback3J_3Finger,0,'open_gde'});

%Defines the entry boxes for the quadratic curves
entry1lab = uicontrol('Style','text', 'Parent', fig, ...
    'Units', 'normalized', ...
    'String', 'Wrench: ', ...
    'Position', [0.285 0.93 0.1 0.05], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'ent1lab', ...
    'Visible', 'off');

%Creates an input box for stiffnes 1
ent1 = uicontrol('Style', 'edit', ...
    'Parent', fig, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.39 0.93 0.05 0.05], ...
    'Tag', 'ent1', ...
    'Visible', 'off');

%Defines the entry boxes for the quadratic curves
entry2lab = uicontrol('Style','text', 'Parent', fig, ...
    'Units', 'normalized', ...
    'String', 'Wrench: ', ...
    'Position', [0.45 0.93 0.1 0.05], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1, 1, 1], ...
    'Tag', 'ent2lab', ...
    'Visible', 'off');

%Creates an input box for stiffnes 1
ent2 = uicontrol('Style', 'edit', ...
    'Parent', fig, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.555 0.93 0.05 0.05], ...
    'Tag', 'ent2', ...
    'Visible', 'off');



%% hp

%Creates a panel for the input
hp = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','hp',...
    'title','Inputs',...
    'BackgroundColor','white',...
    'Position',[0.01 0.02 0.25 0.9]);

%Creates a table for the user to input the compliance matrix
table = uitable('units','normalized',...
            'parent',hp,...
            'position',[0.1 0.782 0.8 0.15],...
            'FontUnits', 'normalized', ...
            'fontsize',0.23,...
            'Data',K,...
            'Rowname',[],...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[true true true],...
            'CellEditCallback',{@UICallback3J_3Finger,ax,'c'},...
            'SelectionHighlight','off',...
            'ColumnWidth',{55 55 55}, ...
            'Tag', 'table');

%Creates a label for the table created right before this
Klab = uicontrol('Style','text', 'Parent',hp, ...
    'Units', 'normalized', ...
    'String', 'Stiffness Matrix', ...
    'Position', [0.1 0.93 0.8 0.04], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.725);

%Creates a label for the x inputs 
xInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.63 0.3 0.05], ...
    'String', 'X', ...
    'Tag', 'XL');

%creates a label for the y inputs
yInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.63 0.3 0.05], ...
    'String', 'Y', ...
    'Tag', 'YL');

%Creates a label for the point 1 inputs 
Pt1Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.58 0.3 0.05], ...
    'String', 'Point 1', ...
    'Tag', 'Pt1L');

%Creates an input box for point 1 x
pt1x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.58 0.3 0.05], ...
    'Tag', 'pt1x');

%creates an input box for point 1 y
pt1y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.58 0.3 0.05], ...
    'Tag', 'pt1y');

%Creates a label for the point 2 inputs
Pt2Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.53 0.3 0.05], ...
    'String', 'Point 2', ...
    'Tag', 'Pt2L');

%creates an input box for point 2 x
pt2x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.53 0.3 0.05], ...
    'Tag', 'pt2x', ...
    'Enable', 'off');

%creates an input box for point 2 y
pt2y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.53 0.3 0.05], ...
    'Tag', 'pt2y', ...
    'Enable', 'off');

%Creates label for the box that shows the cursor x position
xlab = uicontrol('Style', 'text', ...
    'Tag', 'xalb', ...
    'String', 'X-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.35 0.385 0.3 0.05]);

%Creates a box that shows the cursor x position
xpos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'xpos', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...
    'Position', [0.35 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates a label for the box that shows the cursor y position
ylab = uicontrol('Style', 'text', ...
    'Tag', 'ylab', ...
    'String', 'Y-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.65 0.385 0.3 0.05]);

%creates a box that shows the cursor y position
ypos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'ypos', ...
    'units', 'Normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...]
    'Position', [0.65 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates the box for updating the axes scalar
scalar = uicontrol('Style','edit','string','6',...
    'parent', hp, ...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.34 0.3 0.05],...
    'tag','dim',...
    'Callback',{@UICallback3J_3Finger,ax,'dim'});                   

%Creates a label for the axes scalar box
scalarlab = uicontrol('Style','text','string','Axes Scaler:',...
    'HorizontalAlignment', 'center', ...
    'parent', hp, ...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.385 0.3 0.05],...
    'tag','dimlabel');

%Creates a reset button
rst = uicontrol('Style','pushbutton',...
    'parent',hp,...
    'String','Reset',...
    'units','normalized',...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'position',[0.55 0.125 0.35 0.09],...
    'fontunits','normalized',...
    'fontsize',0.5,...
    'tag','reset',...
    'value',0,...
    'Callback',{@UICallback3J_3Finger,ax,'reset'});

%Creates the submit button
sbmt = uicontrol('Style', 'pushbutton', ...
    'Parent', hp, 'Units', 'normalized', ...
    'Position', [0.1 0.125 0.35 0.09], ...
    'String', 'Submit', ...
    'Tag', ' Submit', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'Callback', {@UICallback3J_3Finger, ax, 'Submit'}); 

%Creates the finish object sketch button
finish_object = uicontrol('Style', 'pushbutton', ...
    'Parent', hp, 'Units', 'normalized', ...
    'Position', [0.1 0.015 0.8 0.09], ...
    'String', 'Finish Object Sketch', ...
    'Tag', 'Finish', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.45, ...
    'Visible', 'on', ...
    'Callback', {@UICallback3J_3Finger, ax, 'Finish'}); 



%% hp2

%Creates a panel for the output
hpout = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','hpout',...
    'title','Outputs',...
    'BackgroundColor','white',...
    'Position',[0.74 0.02 0.25 0.95]);


%creates a label for the table above
linLab = uicontrol('Style','text', ...
    'Parent',hpout, ...
    'Units', 'normalized', ...
    'String', 'Spring Line of Action Equations', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.94 0.9 0.04], ...
    'Tag', 'linLab');

%creates an ouput box for line equation 1
lin1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.899 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin1');

%Creates a label for line equation 1
lin1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.899 0.25 0.04], ...
    'Tag', 'lin1Lab');

%creates an ouput box for line equation 2
lin2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.858 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin2');

%Creates a label for line 2 equation
lin2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.858 0.25 0.04], ...
    'Tag', 'lin2Lab');

%creates an ouput box for line equation 3
lin3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.818 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin3');

%Creates a label for line 3 equation
lin3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.818 0.25 0.04], ...
    'Tag', 'lin3Lab');


%creates an ouput box for line equation 4
lin4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.777 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin4');

%Creates a label for line 4 equation
lin4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 4', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.777 0.25 0.04], ...
    'Tag', 'lin4Lab');

%Creates an output box for lin equation 5
lin5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.736 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin5');

%Creates a label for line 5 equation
lin5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 5', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.736 0.25 0.04], ...
    'Tag', 'lin5Lab');

%Creates an output box for lin equation 6
lin6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.695 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'lin6');

%Creates a label for line 6 equation
lin6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 6', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.695 0.25 0.04], ...
    'Tag', 'lin6Lab');

%Creates a label for the spring wrenches
wrenchlab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Transpose Spring Wrenches', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.638 0.9 0.04], ...
    'Tag', 'wrenchLab');

%creates an ouput box for spring wrench 1
wrench1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.597 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench1');

%Creates a label for spring wrench 1
wrench1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.597 0.25 0.04], ...
    'Tag', 'wrench1Lab');

%creates an ouput box for spring wrench 2
wrench2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.556 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench2');

%Creates a label for spring wrench 2
wrench2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.556 0.25 0.04], ...
    'Tag', 'wrench2Lab');

%creates an ouput box for spring wrench 3
wrench3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.515 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench3');

%Creates a label for spring wrench 3
wrench3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.515 0.25 0.04], ...
    'Tag', 'wrench3Lab');

%creates an ouput box for spring wrench 4
wrench4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.475 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench4');

%Creates a label for spring wrench 3
wrench4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 4', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.475 0.25 0.04], ...
    'Tag', 'wrench4Lab');

%creates an ouput box for spring wrench 5
wrench5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.438 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench5');

%Creates a label for spring wrench 5
wrench5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 5', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.435 0.25 0.04], ...
    'Tag', 'wrench5Lab');

%creates an ouput box for spring wrench 6
wrench6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.395 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'wrench6');

%Creates a label for spring wrench 6
wrench6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 6', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.395 0.25 0.04], ...
    'Tag', 'wrench6Lab');

%Creates a label for the spring stiffnesses
stiffLab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring Stiffness', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.338 0.9 0.04], ...
    'Tag', 'stiffLab');

%creates an ouput box for spring stiffness 1
stiff1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.298 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff1');

%Creates a label for spring stiffness 1
stiff1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.298 0.25 0.04], ...
    'Tag', 'stiff1Lab');

%creates an ouput box for Spring stiffness 2
stiff2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.257 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff2');

%Creates a label for spring 2 stiffness
stiff2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.257 0.25 0.04], ...
    'Tag', 'stiff2Lab');

%creates an ouput box for spring stiffness 3
stiff3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.217 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff3');

%Creates a label for spring stiffness 3
stiff3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.217 0.25 0.04], ...
    'Tag', 'stiff3Lab');


%creates an ouput box for spring stifffness 4
stiff4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.75 0.298 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff4');

%Creates a label for spring stiffness 4
stiff4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 4', ...
    'FontSize', 0.7, ...
    'Position', [0.5 0.298 0.25 0.04], ...
    'Tag', 'stiff4Lab');

%creates an ouput box for spring stifffness 5
stiff5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.75 0.257 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff5');

%Creates a label for spring stiffness 5
stiff5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 5', ...
    'FontSize', 0.7, ...
    'Position', [0.5 0.257 0.25 0.04], ...
    'Tag', 'stiff5Lab');

%creates an ouput box for spring stifffness 6
stiff6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.75 0.217 0.2 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'stiff6');

%Creates a label for spring stiffness 6
stiff6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Spring 6', ...
    'FontSize', 0.7, ...
    'Position', [0.5 0.217 0.25 0.04], ...
    'Tag', 'stiff6Lab');

%Creates a table to output the calculated stiffness matrix
Kout = uitable('units','normalized',...
            'parent',hpout,...
            'Tag', 'Kout', ...
            'position',[0.1 0.02 0.8 0.15],...
            'Data',{'', '', ''; '', '', ''; '', '', ''},...
            'Rowname',[],...
            'FontUnits','normalized', ...
            'FontSize', 0.2, ...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[false false false],... 
            'SelectionHighlight','off');

%creates a label for the K out table 
Klab = uicontrol('Style','text', 'Parent',hpout, ...
    'Units', 'normalized', ...
    'String', 'Calculated Siffness Matrix', ...
    'Position', [0.1 .1675 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);


%% Dual Mechanism UI blocks

%Creates a button to convert the mechanics to multiserial
cvt = uicontrol('Style', 'pushbutton', ...
    'Parent', fig, 'Units', 'normalized', ...
    'Position', [0.61 0.93 0.1 0.05], ...
    'String', 'Synthesize Fingers', ...
    'Tag', 'cvt', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.35, ...
    'Visible', 'off', ...
    'Callback', {@UICallback3J_3Finger, ax, 'cvt'});


        %% finger length inputs

        %Creates a table for the user to input the compliance matrix
Lengthtable = uitable('units','normalized',...
            'parent',hp,...
            'position',[0.025 0.5 0.95 0.2],...
            'FontUnits', 'normalized', ...
            'fontsize',0.2,...
            'Data',{'', '', ''; '', '', ''; '', '', ''},...
            'ColumnName',{'Length 1', 'Length 2', 'Length 3'},...
            'RowName',{'Finger1', 'Finger 2', 'Finger 3'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[true true true],... 
            'SelectionHighlight','off',...
            'ColumnWidth',{65 65 65}, ...
            'Tag', 'LenTable', ...
            'Visible', 'off');

%Creates a label for the table created right before this
Lenlab = uicontrol('Style','text', 'Parent',hp, ...
    'Units', 'normalized', ...
    'String', 'Link Lengths', ...
    'Position', [0.025 0.7 0.95 0.04], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.725, ...
    'Visible', 'off', ...
    'Tag', 'LenLab');


        %% tables
%Creates initial output data for the joint position table
[Cx, Cy, ~] = stiffnessCenter(K, ax);
cx = sprintf('%0.3f', Cx);
cy = sprintf('%0.3f', Cy);
Jout1 = {cx,'','','';
       cy,'','',''};

Jout2 = {'','','';
       '','',''};

Jout3 = {'','','';
       '','',''};

%Creates the output table for the joint positions
Jtab1 = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.84 0.9 0.1],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',Jout1,...
            'tag','jout1',...
            'Rowname',{'X','Y'},...
            'ColumnName',{'Cc','J1','J2','J3'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off', ...
            'Visible', 'off');

%Creates the output table for the joint positions
Jtab2 = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.66 0.9 0.1],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',Jout2,...
            'tag','jout2',...
            'Rowname',{'X','Y'},...
            'ColumnName',{'J1', 'J2', 'J3'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off', ...
            'Visible', 'off');

%Creates the output table for the joint positions
Jtab3 = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.48 0.9 0.1],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',Jout3,...
            'tag','jout3',...
            'Rowname',{'X','Y'},...
            'ColumnName',{'J1', 'J2', 'J3'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off', ...
            'Visible', 'off');



%creates a label for the output table 
Jlab1 = uicontrol('Style','text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'String', 'Finger 1 Joint Positions', ...
    'FontUnits','normalized', ...
    'FontSize', 0.65, ...
    'Position', [0.05 0.94 0.9 0.04], ...
    'Tag', 'jlab1', ...
    'Visible', 'off');

%creates a label for the output table 
Jlab2 = uicontrol('Style','text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'String', 'Finger 2 Joint Positions', ...
    'FontUnits','normalized', ...
    'FontSize', 0.65, ...
    'Position', [0.05 0.76 0.9 0.04], ...
    'Tag', 'jlab2', ...
    'Visible', 'off');

%creates a label for the output table 
Jlab3 = uicontrol('Style','text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'String', 'Finger 3 Joint Positions', ...
    'FontUnits','normalized', ...
    'FontSize', 0.65, ...
    'Position', [0.05 0.58 0.9 0.04], ...
    'Tag', 'jlab3', ...
    'Visible', 'off');

%% Sepetartion condition toggle 

sepCond1 = uicontrol('Style', 'pushbutton', ...
    'Parent', fig, 'Units', 'normalized', ...
    'Position', [0.325 0.93 0.1 0.05], ...
    'String', 'Joint 1 Condition', ...
    'Tag', 'J1C', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.35, ...
    'Visible', 'off', ...
    'Callback', {@UICallback3J_3Finger, ax, 'J1C'});

sepCond2 = uicontrol('Style', 'pushbutton', ...
    'Parent', fig, 'Units', 'normalized', ...
    'Position', [0.45 0.93 0.1 0.05], ...
    'String', 'Joint 2 Condition', ...
    'Tag', 'J2C', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.35, ...
    'Visible', 'off', ...
    'Callback', {@UICallback3J_3Finger, ax, 'J2C'});

sepCond3 = uicontrol('Style', 'pushbutton', ...
    'Parent', fig, 'Units', 'normalized', ...
    'Position', [0.575 0.93 0.1 0.05], ...
    'String', 'Joint 3 Condition', ...
    'Tag', 'J3C', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.35, ...
    'Visible', 'off', ...
    'Callback', {@UICallback3J_3Finger, ax, 'J3C'});

        %% compliances
%Creates a label for the joint compliances
compLab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint Compliances', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.4 0.9 0.04], ...
    'Tag', 'compLab', ...
    'Visible', 'off');


%Creates the output table for the joint positions
Ctab1 = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.25 0.9 0.15],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',{'', '', ''; '', '', ''; '', '', ''},...
            'tag','cout1',...
            'Rowname',{'Comp 1','Comp 2', 'Comp 3'},...
            'ColumnName',{'Finger 1', 'Finger 2', 'Finger 3'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off', ...
            'Visible', 'off');


%%

%Displays the stiffness center on the plot
[x,y,K] = stiffnessCenter(K, ax);

%Sets the size and position of the main window
resolution = get(0,'screensize');
set(fig,'position',[resolution(3)/12,resolution(4)/8,1200,670]);

%Opens the guide window
guide3J_3Finger()

set(fig,'visible','on'); hold on;
set(gcf,'menubar','figure');


end

