function [] = Synthesis4J()

addpath('PlanarComplianceApp/Serial4JSynthesis/')
addpath('PlanarComplianceApp/General_Functions/')
clearvars -global

%Phase 1 - Nothing has happened

%Phase 2 - The first handle for line l1 (tag 'N1') has been placed on the axes

%Phase 3 - The second handle for line l1 (tag 'N2') has been placed on the
%axes, line l1 has been places on the axes, and the first twist center (T1) has
%been calculates and place on the axes

%Phase 4 - The handle for line l2 has been drawn (tag 'N3'), the line l2 has been
%drawn, twist center two (T2) has been placed, and the segment between T1
%and T2 has been placed

%Phase 5 - The first handle for line l3 (tag 'N4') has been placed

%Phase 6 - The second handle for line l3 (tag 'N5') has been placed, line
%l3 has been drawn, and twist center T3 has been placed.

%Phase 7 - Everything has been placed

global phase dragN dragL C
C = inv([3 -2 1; -2 6 5; 1 5 9]);
phase = 1;
dragN = [0;0;0;0;0;0;0];
dragL = [0;0;0;0];

%Creates the 4J figure
fig = figure(1); clf;
set(fig,'Name','Realization of a 4 Joint Serial Mechanism','NumberTitle','on');
set(fig,'units','normalized');
set(fig,'renderer','OpenGL','visible','off');
set(fig,'SizeChangedFcn', {@cTableResize, fig});
pan on;
pan off;

z = 6;
ax = axes();
linkaxes(ax);
axis([-z z -z z]);
set(ax,'units','normalized')
set(ax, 'Parent', fig)
set(ax,'Position',[0.285, 0.05, 0.43, 0.9])
set(ax, 'PickableParts', 'all')
grid on; grid minor; box on;
axis equal; hold on;

set(ax,'XLimMode','manual');
set(ax,'YLimMode','manual');
set(ax,'ButtonDownFcn',{@MouseClick, ax});
set(fig,'WindowButtonMotionFcn',{@MouseDrag, ax});
set(fig,'WindowButtonUpFcn',@MouseRelease);
set(fig,'menubar','none'); 
origin = scatter(0,0,'+','markerfacecolor',[0 0 0],'sizedata',120,'markeredgecolor',[0 0 0]);
uistack(origin, 'bottom');

p1 = plot([0, 0], [0.0001, 0], 'Color', [0.2 0.6 1], 'LineWidth', 2);
p2 = plot([0, 0], [0.0001, 0], 'Color', [0.3 0.9 0.3], 'LineWidth', 2);
p3 = plot([0, 0], [0.0001, 0], 'Color', [0.9 0.3 0.3], 'LineWidth', 2);
p4 = plot([0, 0], [0.0001, 0], 'Color', [0.9 0.9 0.3], 'LineWidth', 2);

leg = legend('', 'L1', 'L2', 'L3', 'L4');
leg.AutoUpdate = "off";

%defines the home button
home = uicontrol('Style', 'pushbutton', ...
    'String','Home','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.65, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.025 0.93 0.1 0.05], ...
    'Callback',{@UIcallback4J,0,'Home'});

open_gde = uicontrol('Style', 'pushbutton', ...
    'String','Open Guide','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.55, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.145 0.93 0.1 0.05], ...
    'Callback',{@UIcallback4J,0,'open_gde'});

%% hp

%Creates the Input panel 
hp = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','panel',...
    'title','Inputs',...
    'BackgroundColor','white', ...
    'Position', [0.01 0.02 0.25 0.9]);

%Creates the table to input the compliance matrix
table = uitable('units','normalized',...
            'parent',hp,...
            'position',[0.1 0.782 0.8 0.15],...
            'FontUnits', 'normalized', ...
            'fontsize', 0.21,...
            'Data',C,...
            'Rowname',[],...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[true true true],...
            'CellEditCallback',{@UIcallback4J,ax,'c'},...
            'SelectionHighlight','off',...
            'ColumnWidth',{55 55 55}, ...
            'Tag', 'table');

%Creates a label for the compliance matrix table 
clab = uicontrol('Style','text', 'Parent',hp, ...
    'Units', 'normalized', ...
    'String', 'Compliance Matrix', ...
    'Position', [0.1 0.93 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);

%Creates a label for the x inputs 
xInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.68 0.3 0.05], ...
    'String', 'X');

%creates a label for the y inputs
yInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.68 0.3 0.05], ...
    'String', 'Y');

%Creates a label for the point 1 inputs 
Pt1Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.63 0.3 0.05], ...
    'String', 'Point 1');

%Creates an input box for point 1 x
pt1x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.63 0.3 0.05], ...
    'Tag', 'pt1x');

%creates an input box for point 1 y
pt1y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.63 0.3 0.05], ...
    'Tag', 'pt1y');

%Creates a label for the point 2 inputs
Pt2Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.58 0.3 0.05], ...
    'String', 'Point 2');

%creates an input box for point 2 x
pt2x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.58 0.3 0.05], ...
    'Tag', 'pt2x');

%creates an input box for point 2 y
pt2y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.58 0.3 0.05], ...
    'Tag', 'pt2y');

%Creates label for the box that shows the cursor x position
xlab = uicontrol('Style', 'text', ...
    'Tag', 'xalb', ...
    'String', 'X-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.35 0.43 0.3 0.05]);

%Creates a box that shows the cursor x position
xpos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'xpos', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...
    'Position', [0.35 0.38 0.3 0.05], ...
    'Enable','inactive');

%Creates a label for the box that shows the cursor y position
ylab = uicontrol('Style', 'text', ...
    'Tag', 'ylab', ...
    'String', 'Y-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.65 0.43 0.3 0.05]);

%creates a box that shows the cursor y position
ypos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'ypos', ...
    'units', 'Normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...]
    'Position', [0.65 0.38 0.3 0.05], ...
    'Enable','inactive');

%Creates the axes scalar
scalar = uicontrol('Style','edit','string','6',...
    'parent', hp,...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.38 0.3 0.05],...
    'tag','dim',...
    'Callback',{@UIcallback4J,ax,'dim'});

%Creates the axes scalar label
scalarlab = uicontrol('Style','text','string','Axes Scaler: ',...
    'parent', hp,...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.45,...
    'HorizontalAlignment','right',...
    'position',[0.025 0.43 0.3 0.05],...
    'tag','dimlabel');

%Creates the submit button
sbmt = uicontrol('Style', 'pushbutton', ...
    'Parent', hp, 'Units', 'normalized', ...
    'Position', [0.1 0.17 0.35 0.09], ...
    'String', 'Submit', ...
    'Tag', ' Submit', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'Callback', {@UIcallback4J, ax, 'Submit'}); 

%Creates the reset button
rst = uicontrol('Style','pushbutton',...
    'parent',hp,...
    'String','Reset',...
    'units','normalized',...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'position',[0.55 0.17 0.35 0.09],...
    'fontunits','normalized',...
    'fontsize',0.5,...
    'tag','reset',...
    'value',0,...
    'Callback',{@UIcallback4J,ax,'reset'});


%% hpout

%Creates the output panel
hpout = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','panelout',...
    'title','Outputs',...
    'BackgroundColor','white', ...
    'Position', [0.74 0.02 0.25 0.9]);

%Creates initial output data for the joint position table
[Cx, Cy, C] = compliantCenter(C, ax);
cx = sprintf('%0.3f', Cx);
cy = sprintf('%0.3f', Cy);
Jout = {cx,'','','','';
        cy,'','','',''};

%Creates the output table for the joint positions
Jtab = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.84 0.9 0.1],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',Jout,...
            'tag','jout',...
            'Rowname',{'X','Y'},...
            'ColumnName',{'Cc','J1','J2','J3','J4'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off');

%creates a label for the output table 
Jlab = uicontrol('Style','text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'String', 'Joint Positions', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.94 0.9 0.04]);

%Creates a label for the joint compliances
compLab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint Compliance', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.72 0.9 0.04]);

%creates an ouput box for joint compliance 1
comp1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.679 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp1');

%Creates a label for joint 1 compliance
comp1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.679 0.25 0.04]);

%creates an ouput box for joint 2 compliance
comp2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.638 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp2');

%Creates a label for joint 2 compliance 
comp2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.638 0.25 0.04]);

%creates an ouput box for joint 3 compliance
comp3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.597 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp3');

%Creates a label for joint 3 compliance
comp3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.597 0.25 0.04]);

%creates an ouput box for joint 4 compliance
comp4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.556 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp4');

%Creates a label for joint 4 compliance
comp4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 4', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.556 0.25 0.04]);

%Creates a table for the Calculated compliance matrix output
Cout = uitable('units','normalized',...
            'parent',hpout,...
            'Tag', 'Cout', ...
            'position',[0.1 0.3 0.8 0.15],...
            'Data',{'', '', ''; '', '', ''; '', '', ''},...
            'Rowname',[],...
            'FontUnits','normalized', ...
            'FontSize', 0.21, ...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[false false false],... 
            'SelectionHighlight','off');

%creats a label for the C out table 
Clab = uicontrol('Style','text', 'Parent',hpout, ...
    'Units', 'normalized', ...
    'String', 'Calculated Compliance Matrix', ...
    'Position', [0.1 0.45 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);

%%




%Plots the compliance center
compliantCenter(C, ax);

%Defines the size and position of the main window
set(fig, 'Units', 'pixels')
resolution = get(0,'screensize');
set(fig,'position',[resolution(3)/12,resolution(4)/8,1200,670]);

%opens the guide window
guide4J

set(fig,'visible','on'); hold on;
set(gcf,'menubar','figure');

end
