function [] = Synthesis6J()

addpath('PlanarComplianceApp/Serial6JSynthesis/')
addpath('PlanarComplianceApp/General_Functions/')
clearvars -global

%Phase = 1 - nothing has happened

%Phase = 2 - second handle of l12 is defined, twist 12 is placed

%Phase = 3 - first handle of l34 is placed

%Phase = 4 - second handle of l34 is placed, twist 34 is placed, the
%condition in step two of the synthesis procedure is checked. The location 
%of Joint 1 has been selected

%Phase = 5 - The location of Joint 2 has been selected

%Phase = 6 - The location of Joint 3 has been selected

%Phase = 7 - The location of Joint 4 has been selected, The condition in
%step 3 has been checked, the quadratic curve has been plotted

%Phase = 8 - Joint 5 has been placed

%Phase = 9 - Joint 6 has been calculated and the remaining conditions have
%been checked. Outputs are displayed


global phase dragN dragL C

C = [0.5 -0.2 0.3; -0.2 0.8 -0.4; 0.3 -0.4 0.5];
dragN = [0, 0, 0, 0, 0, 0];
dragL = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
phase = 1;



%Creates the 6J figure
fig = figure(1); clf;
set(fig,'Name','Realization of a 6 Joint Serial Mechanism','NumberTitle','on');
set(fig,'units','normalized');
set(fig,'renderer','OpenGL','visible','off');
set(fig,'SizeChangedFcn', {@cTableResize, fig});

pan on;
pan off;

z = 6;

ax = axes();
linkaxes(ax);
axis([-z z -z z]);
set(ax,'units','normalized')
set(ax,'Position',[0.285, 0.05, 0.43, 0.9])
grid on; grid minor; box on;
axis equal; hold on;

set(ax,'XLimMode','manual');
set(ax,'YLimMode','manual');
set(fig,'WindowButtonDownFcn', {@MouseClick, ax})
set(fig,'WindowButtonMotionFcn', {@MouseDrag, ax})
set(fig,'WindowButtonUpFcn', @MouseRelease)
set(fig,'menubar','none'); 
origin = scatter(0,0,'+','markerfacecolor',[0 0 0],'sizedata',120,'markeredgecolor',[0 0 0]);
uistack(origin, 'bottom');

p1 = plot([0, 0], [0.0001, 0], 'Color', [0 0.4470 0.7410], 'LineWidth', 2);
p2 = plot([0, 0], [0.0001, 0], 'Color', [0.9290 0.6940 0.1250], 'LineWidth', 2);

leg = legend('', 'wrench 1', 'wrench 2');
leg.AutoUpdate = "off";

%defines the home button
home = uicontrol('Style', 'pushbutton', ...
    'String','Home','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.65, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.025 0.93 0.1 0.05], ...
    'Callback',{@UICallback6J,0,'Home'});

open_gde = uicontrol('Style', 'pushbutton', ...
    'String','Open Guide','Units', 'Normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.55, ...
    'BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'Position',[0.145 0.93 0.1 0.05], ...
    'Callback',{@UICallback6J,0,'open_gde'});

%% hp

%Creates the Input panel 
hp = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','panel',...
    'title','Inputs',...
    'BackgroundColor','white', ...
    'Position', [0.01 0.02 0.25 0.9]);


%Creates the table to input the compliance matrix
table = uitable('units','normalized',...
            'parent',hp,...
            'position',[0.1 0.782 0.8 0.15],...
            'FontUnits', 'normalized', ...
            'fontsize', 0.21,...
            'Data',C,...
            'Rowname',[],...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[true true true],... 
            'CellEditCallback',{@UICallback6J, ax, 'c'},...
            'SelectionHighlight','off',...
            'ColumnWidth',{55 55 55}, ...
            'Tag', 'table');

%Creates a label for the compliance matrix table 
clab = uicontrol('Style','text', 'Parent',hp, ...
    'Units', 'normalized', ...
    'String', 'Compliance Matrix', ...
    'Position', [0.1 0.93 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);

%Creates a label for the x inputs 
xInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.63 0.3 0.05], ...
    'String', 'X');

%creates a label for the y inputs
yInLab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.63 0.3 0.05], ...
    'String', 'Y');

%Creates a label for the point 1 inputs 
Pt1Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.58 0.3 0.05], ...
    'String', 'Point 1');

%Creates an input box for point 1 x
pt1x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '0', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.58 0.3 0.05], ...
    'Tag', 'pt1x', ...
    'Enable', 'off');

%creates an input box for point 1 y
pt1y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '0', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.58 0.3 0.05], ...
    'Tag', 'pt1y', ...
    'Enable', 'off');

%Creates a label for the point 2 inputs
Pt2Lab = uicontrol('Style', 'text', ...
    'Parent', hp, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.025 0.53 0.3 0.05], ...
    'String', 'Point 2');

%creates an input box for point 2 x
pt2x = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.325 0.53 0.3 0.05], ...
    'Tag', 'pt2x');

%creates an input box for point 2 y
pt2y = uicontrol('Style', 'edit', ...
    'Parent', hp, ...
    'String', '', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'Position', [0.625 0.53 0.3 0.05], ...
    'Tag', 'pt2y');


%Creates the axes scalar
scalar = uicontrol('Style','edit','string','6',...
    'parent', hp,...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.5,...
    'position',[0.025 0.34 0.3 0.05],...
    'tag','dim', ...
    'Callback', {@UICallback6J, ax, 'dim'});

%Creates the axes scalar label
scalarlab = uicontrol('Style','text','string','Axes Scaler: ',...
    'parent', hp,...
    'units','normalized',...
    'fontunits','normalized',...
    'fontsize', 0.45,...
    'HorizontalAlignment','right',...
    'position',[0.025 0.385 0.3 0.05],...
    'tag','dimlabel');

%Creates label for the box that shows the cursor x position
xlab = uicontrol('Style', 'text', ...
    'Tag', 'xalb', ...
    'String', 'X-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.35 0.385 0.3 0.05]);

%Creates a box that shows the cursor x position
xpos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'xpos', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...
    'Position', [0.35 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates a label for the box that shows the cursor y position
ylab = uicontrol('Style', 'text', ...
    'Tag', 'ylab', ...
    'String', 'Y-Position', ...
    'Units', 'normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.5, ...
    'Parent', hp, ...
    'Position', [0.65 0.385 0.3 0.05]);

%creates a box that shows the cursor y position
ypos = uicontrol('Style', 'edit', ...
    'String', '', 'tag', 'ypos', ...
    'units', 'Normalized', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Parent', hp, ...]
    'Position', [0.65 0.34 0.3 0.05], ...
    'Enable','inactive');

%Creates the submit button
sbmt = uicontrol('Style', 'pushbutton', ...
    'Parent', hp, 'Units', 'normalized', ...
    'Position', [0.1 0.16 0.35 0.09], ...
    'String', 'Submit', ...
    'Tag', ' Submit', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1], ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.5, ...
    'Callback', {@UICallback6J, ax, 'Submit'}); 

%Creates the reset button
rst = uicontrol('Style','pushbutton',...
    'parent',hp,...
    'String','Reset',...
    'units','normalized',...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'position',[0.55 0.16 0.35 0.09],...
    'fontunits','normalized',...
    'fontsize',0.5,...
    'tag','reset',...
    'value',0, ...
    'Callback', {@UICallback6J, ax, 'reset'});





%% hp2

%Creates the output panel
hpout = uipanel('FontSize',10,...
    'units','normalized',...
    'tag','panelout',...
    'title','Outputs',...
    'BackgroundColor','white', ...
    'Position', [0.74 0.02 0.25 0.9]);

%Creates initial output data for the joint position table
[Cx, Cy, ~] = compliantCenter(C, ax);
cx = sprintf('%0.3f', Cx);
cy = sprintf('%0.3f', Cy);
Jout1 = {cx,'','';
       cy,'',''};

Jout2 = {'','','';
       '','',''};

%Creates the output table for the joint positions
Jtab1 = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.84 0.9 0.1],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',Jout1,...
            'tag','jout',...
            'Rowname',{'X','Y'},...
            'ColumnName',{'Cc','J1','J2'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off');

%Creates the output table for the joint positions
Jtab2 = uitable('units','normalized',...
            'parent',hpout,...
            'position',[0.05 0.73 0.9 0.1],...
            'FontUnits', 'normalized', ...
            'fontsize',0.15,...
            'Data',Jout2,...
            'tag','jout2',...
            'Rowname',{'X','Y'},...
            'ColumnName',{'J3', 'J4', 'J5', 'J6'},...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'SelectionHighlight','off');



%creates a label for the output table 
Jlab = uicontrol('Style','text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'String', 'Joint Positions', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.94 0.9 0.04]);

%Creates a label for the joint compliances
compLab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint Compliance', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.62 0.9 0.04]);


%creates an ouput box for joint compliance 1
comp1 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', '  ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.579 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp1');

%Creates a label for joint 1 compliance
comp1lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 1', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.579 0.25 0.04]);

%creates an ouput box for joint 2 compliance
comp2  = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.538 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp2');

%Creates a label for joint 2 compliance 
comp2lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 2', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.538 0.25 0.04]);

%creates an ouput box for joint 3 compliance
comp3 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.497 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp3');

%Creates a label for joint 3 compliance
comp3lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 3', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.497 0.25 0.04]);

%creates an ouput box for joint 4 compliance
comp4 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.456 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp4');

%Creates a label for joint 4 compliance
comp4lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 4', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.456 0.25 0.04]);

%creates an ouput box for joint 5 compliance
comp5 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.415 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp5');

%Creates a label for joint 5 compliance
comp5lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 5', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.415 0.25 0.04]);

%creates an ouput box for joint 6 compliance
comp6 = uicontrol('Style', 'text', ...
    'Parent', hpout, ...
    'String', ' ', ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'FontSize', 0.7, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'Position', [0.3 0.374 0.65 0.04], ...
    'HorizontalAlignment','left', ...
    'Tag', 'comp6');

%Creates a label for joint 6 compliance
comp6lab = uicontrol('Style', 'Text', ...
    'Parent', hpout, ...
    'Units', 'normalized', ...
    'FontUnits', 'normalized', ...
    'String', 'Joint 6', ...
    'FontSize', 0.7, ...
    'Position', [0.05 0.374 0.25 0.04]);


%Creates a table for the Calculated compliance matrix output
Cout = uitable('units','normalized',...
            'parent',hpout,...
            'Tag', 'Cout', ...
            'position',[0.1 0.1 0.8 0.15],...
            'Data', {'', '', ''; '', '', ''; '', '', ''},...
            'Rowname',[],...
            'FontUnits','normalized', ...
            'FontSize', 0.21, ...
            'ColumnName',[],...
            'ColumnFormat',{'numeric' 'numeric' 'numeric'},...
            'RowStriping','off',...
            'ColumnEditable',[false false false],... 
            'SelectionHighlight','off');

%creats a label for the C out table 
Clab = uicontrol('Style','text', 'Parent',hpout, ...
    'Units', 'normalized', ...
    'String', 'Calculated Compliance Matrix', ...
    'Position', [0.1 0.25 0.8 0.03], ...
    'HorizontalAlignment', 'center', ...
    'FontUnits','normalized', ...
    'FontSize', 0.7);



%%

%Displays the compliance center on the plot
[x, y, C] = compliantCenter(C, ax);
scatter(x,y,'*','markerfacecolor','red','sizedata',100,'markeredgecolor','red','tag','cpoint');

%Positions and sets the size of the main window
set(fig, 'Units', 'pixels')
resolution = get(0,'screensize');
set(fig,'position',[resolution(3)/12,resolution(4)/8,1200,670]);

%Sets the location of the first joint
drawPoint(ax, 'N1', 0, 0)

%Opens the guide window
guide6J()

set(fig,'visible','on'); hold on
set(gcf,'menubar','figure');

end